### ISSUE TITLE
Implement WIFI-connection

### ISSUE THREAD

**Issue by linusivarssons** [DIT112-V20/group-02#31]
As a user, I want to be able to connect to the car via WIFI, so that I can control it. 

Acceptance critera:
- Able to connect device to car via WIFI.

**Comment by Brother-Blue** [comment]
Reverting to bluetooth connection.

**Comment by platisd** [comment]
> Reverting to bluetooth connection.

It's ultimately your choice, but can you elaborate on why?

**Comment by Brother-Blue** [comment]
We've been having constant issues with trying to connect to the car with different wifi connectivity techniques (nds, volley, mdns). Instead of potentially wasting time and trying to get wifi to work, it seemed more efficient to go back to bluetooth communication which works fine.

**Comment by platisd** [comment]
Where was the problem exactly? Those libraries or technologies you mentioned do different things.

**Comment by Brother-Blue** [comment]
NDS was having an issue where it would send out a listener to discover the web server but it never found anything, tried with the default http, tcp, 80 and using custom names.

Volley gave errors saying the smartcar.local did not have a valid protocol

MDNS we switched away from since android does not have a clear way of handling it and any documentation we found pointed back to NDS.

**Comment by platisd** [comment]
Indeed, resolving the host name is naturally a precondition for the others to work.
I'll try to see if I can create an example for (future) reference.

**Comment by platisd** [comment]
You can resolve `.local` addresses by using a small utility class like this [one](https://github.com/DIT112-V20/kotlin-app-arduino-sketch-ci/blob/master/android/LocalDeviceNameResolution/app/src/main/java/platis/solutions/localDeviceNameResolution/LocalNetworkDeviceNameResolver.java). So I'd suggest giving WiFi another try but it's ultimately up to you.
